/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonnaci sequence whose values do not exceed four million, find the sum of teh even-valued terms.
 */

#include<algorithm>
#include<iostream>

int main(void) {
	int sum{};

	int a{1};
	int b{2};

	int limit = 4000000;

	while (a <= limit) {
		if (a % 2 == 0) sum += a;
		a += b;
		std::swap(a, b);
	}

	std::cout << "Sum of even-valued Fibonacci terms that not exceed 4,000,000: " << sum << std::endl;

	return 0;
}
